FROM node:22-alpine
LABEL "language"="nodejs"
LABEL "framework"="vue.js"

WORKDIR /src

RUN npm install -f -g pnpm@9

COPY . .

RUN pnpm install

RUN pnpm --filter=@interview/vue-app build

EXPOSE 8080

CMD ["npx", "serve", "-s", "apps/vue-app/dist", "-l", "8080"]
